# Generated by Django 3.2.6 on 2021-09-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0012_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendliness', models.CharField(max_length=100, null=True)),
                ('knowledge', models.CharField(max_length=100, null=True)),
                ('quickness', models.CharField(max_length=100, null=True)),
                ('infuture', models.CharField(max_length=30, null=True)),
                ('suggestion', models.CharField(max_length=300, null=True)),
                ('feedbackdate', models.DateField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_service.order')),
            ],
        ),
    ]
