# Generated by Django 5.0.4 on 2024-04-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0013_servicefeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
